FROM openjdk:8-jdk-alpine
EXPOSE 8082
ADD /target/EMPLOYEES-MICROSERVICES-0.0.1-SNAPSHOT.jar EMPLOYEES-MICROSERVICES-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "EMPLOYEES-MICROSERVICES-0.0.1-SNAPSHOT.jar"]